### ISSUE TITLE
Is this compliant with challenge?

### ISSUE THREAD

**Issue by alexpyattaev** [tumdum/1brc#1]
Technically, you are using a bunch of crates, and official rules say standard library only. Were these specific crates approved?

**Comment by diepes** [comment]
I don't think it matters much as the challenge is over and was focused on Java with a huge standard library.

I love the cleanness of this solution and it is fast.
I got my best effort to 22sec, and this runs 4-5sec flat. (With a unsafe -  memmap file) 🥇

**Comment by alexpyattaev** [comment]
Yeah, same sort of result for me, not using the crates.io stuff makes this far far harder, and teaches one to appreciate the libraries we take for granted. I'm still trying to figure out why the  C solution is like 3x faster though, seems to be due to custom hashing function, but I'm not quite sure.
